-module(openagentic_web_case_governance_static_page_test).

-include_lib("eunit/include/eunit.hrl").

-import(openagentic_web_case_governance_test_support, [
  append_round_result/3,
  reset_web_runtime/0,
  maybe_kill/1,
  ensure_httpc_started/0,
  http_post_json/2,
  http_get_json/1,
  http_get_text/1,
  contains_codepoints/2,
  deep_get_bin/2,
  deep_get_int/2,
  tmp_root/0,
  pick_port/0,
  ensure_map/1,
  ensure_list/1,
  to_bin/1
]).

case_governance_static_page_test() ->
  Root = tmp_root(),
  Port = pick_port(),
  PrevTrap = process_flag(trap_exit, true),
  ensure_httpc_started(),
  try
    {ok, _} = openagentic_web:start(#{project_dir => Root, session_root => Root, web_bind => "127.0.0.1", web_port => Port}),
    Base = ensure_list(openagentic_web:base_url(#{bind => "127.0.0.1", port => Port})),
    {200, Html} = http_get_text(Base ++ "view/cases.html"),
    {200, GovernanceHtml} = http_get_text(Base ++ "view/governance-session.html"),
    {200, TaskDetailHtml} = http_get_text(Base ++ "view/task-detail.html"),
    {200, InboxHtml} = http_get_text(Base ++ "view/inbox.html"),
    {200, ReconsiderationHtml} = http_get_text(Base ++ "view/reconsideration-preview.html"),
    {200, IndexHtml} = http_get_text(Base),
    {200, AppCss} = http_get_text(Base ++ "assets/app.css"),
    {200, CaseCss} = http_get_text(Base ++ "assets/case-governance.css"),
    {200, AppJs} = http_get_text(Base ++ "assets/app.js"),
    {200, CaseJs} = http_get_text(Base ++ "assets/case-governance.js"),
    {200, TaskJs} = http_get_text(Base ++ "assets/task-detail.js"),
    {200, GovernanceJs} = http_get_text(Base ++ "assets/governance-session.js"),
    {200, InboxJs} = http_get_text(Base ++ "assets/inbox.js"),
    {200, ReconsiderationJs} = http_get_text(Base ++ "assets/reconsideration-preview.js"),
    {200, TopbarJs} = http_get_text(Base ++ "assets/topbar.js"),
    AppCssWithoutMinHeight = string:replace(AppCss, "min-height: 100vh", "", all),
    ?assert(string:find(Html, "caseCreateForm") =/= nomatch),
    ?assert(string:find(Html, "caseLifecycleNote") =/= nomatch),
    ?assert(string:find(Html, "btnExtractCandidates") =/= nomatch),
    ?assert(string:find(Html, "candidateList") =/= nomatch),
    ?assert(string:find(Html, "templateCreateForm") =/= nomatch),
    ?assert(string:find(Html, "templateList") =/= nomatch),
    ?assert(string:find(Html, "inboxLink") =/= nomatch),
    ?assert(string:find(Html, "inboxUnreadBadge") =/= nomatch),
    ?assert(string:find(Html, "caseBreadcrumb") =/= nomatch),
    ?assert(string:find(Html, "caseNextAction") =/= nomatch),
    ?assert(string:find(Html, "contextHelp") =/= nomatch),
    ?assert(string:find(Html, "\x{67e5}\x{770b}\x{7acb}\x{6848}\x{8bf4}\x{660e}") =/= nomatch),
    ?assert(string:find(Html, "caseWorkspaceGuide") =/= nomatch),
    ?assert(string:find(Html, "panelLead") =/= nomatch),
    ?assert(string:find(Html, "data-case-workspace") =/= nomatch),
    ?assert(string:find(Html, "/assets/case-governance.js") =/= nomatch),
    ?assert(contains_codepoints(Html, [26696, 21367, 20837, 21475])),
    ?assert(string:find(GovernanceHtml, "governanceSessionForm") =/= nomatch),
    ?assert(string:find(GovernanceHtml, "governanceRevisionForm") =/= nomatch),
    ?assert(string:find(GovernanceHtml, "governanceTaskSummary") =/= nomatch),
    ?assert(string:find(GovernanceHtml, "governanceVersionDiff") =/= nomatch),
    ?assert(string:find(GovernanceHtml, "governanceCredentialBindingForm") =/= nomatch),
    ?assert(string:find(GovernanceHtml, "governanceActivateTask") =/= nomatch),
    ?assert(string:find(GovernanceHtml, "revisionCredentialSlotName") =/= nomatch),
    ?assert(string:find(GovernanceHtml, "governanceBreadcrumb") =/= nomatch),
    ?assert(string:find(GovernanceHtml, "governanceNextAction") =/= nomatch),
    ?assert(string:find(GovernanceHtml, "governanceConversationPanel") =/= nomatch),
    ?assert(string:find(GovernanceHtml, "contextHelp") =/= nomatch),
    ?assert(string:find(GovernanceHtml, "Cases / \x{6cbb}\x{7406}\x{4f1a}\x{8bdd}") =/= nomatch),
    ?assert(string:find(GovernanceHtml, "\x{8fd4}\x{56de}\x{4efb}\x{52a1}\x{8be6}\x{60c5}") =/= nomatch),
    ?assert(string:find(GovernanceHtml, "inboxUnreadBadge") =/= nomatch),
    ?assert(string:find(GovernanceHtml, "emptyState") =/= nomatch),
    ?assert(string:find(GovernanceHtml, "panelLead") =/= nomatch),
    ?assert(string:find(GovernanceHtml, "/assets/governance-session.js") =/= nomatch),
    ?assert(contains_codepoints(GovernanceHtml, [27835, 29702, 20250, 35805])),
    ?assert(string:find(TaskDetailHtml, "taskDetailView") =/= nomatch),
    ?assert(string:find(TaskDetailHtml, "taskVersionDiff") =/= nomatch),
    ?assert(string:find(TaskDetailHtml, "contextHelp") =/= nomatch),
    ?assert(string:find(TaskDetailHtml, "\x{4efb}\x{52a1}\x{8be6}\x{60c5}\x{4f18}\x{5148}") =/= nomatch),
    ?assert(string:find(TaskDetailHtml, "inboxUnreadBadge") =/= nomatch),
    ?assert(string:find(TaskDetailHtml, "inboxLink") =/= nomatch),
    ?assert(string:find(TaskDetailHtml, "taskBreadcrumb") =/= nomatch),
    ?assert(string:find(TaskDetailHtml, "taskNextAction") =/= nomatch),
    ?assert(string:find(TaskDetailHtml, "taskVersionDiffPanel") =/= nomatch),
    ?assert(string:find(TaskDetailHtml, "taskRunAttemptsPanel") =/= nomatch),
    ?assert(string:find(TaskDetailHtml, "taskFactReportsPanel") =/= nomatch),
    ?assert(string:find(TaskDetailHtml, "emptyState") =/= nomatch),
    ?assert(string:find(TaskDetailHtml, "panelLead") =/= nomatch),
    ?assert(string:find(TaskDetailHtml, "/assets/task-detail.js") =/= nomatch),
    ?assert(contains_codepoints(TaskDetailHtml, [20219, 21153, 35814, 24773])),
    ?assert(string:find(InboxHtml, "\x{96c6}\x{4e2d}\x{67e5}\x{770b}\x{6848}\x{5377}\x{6d88}\x{606f}") =/= nomatch),
    ?assert(string:find(InboxHtml, "contextHelp") =/= nomatch),
    ?assert(string:find(InboxHtml, "\x{5168}\x{5c40}\x{5185}\x{90ae}") =:= nomatch),
    ?assert(string:find(InboxHtml, "inboxFilterForm") =/= nomatch),
    ?assert(string:find(InboxHtml, "inboxReturnLink") =/= nomatch),
    ?assert(string:find(InboxHtml, "`n") =:= nomatch),
    ?assert(string:find(InboxHtml, "inboxUnreadBadge") =/= nomatch),
    ?assert(string:find(InboxHtml, "globalMailList") =/= nomatch),
    ?assert(string:find(InboxHtml, "/assets/inbox.js") =/= nomatch),
    ?assert(contains_codepoints(InboxHtml, [32479, 19968, 20449, 31665])),
    ?assert(string:find(ReconsiderationHtml, "reconsiderationPreview") =/= nomatch),
    ?assert(string:find(ReconsiderationHtml, "btnStartReconsideration") =/= nomatch),
    ?assert(string:find(ReconsiderationHtml, "btnDeferReconsideration") =/= nomatch),
    ?assert(string:find(ReconsiderationHtml, "reconsiderationLifecycleHint") =/= nomatch),
    ?assert(string:find(ReconsiderationHtml, "reconsiderationBaselinePanel") =/= nomatch),
    ?assert(string:find(ReconsiderationHtml, "reconsiderationChangesPanel") =/= nomatch),
    ?assert(string:find(ReconsiderationHtml, "reconsiderationControversiesPanel") =/= nomatch),
    ?assert(string:find(ReconsiderationHtml, "reconsiderationBreadcrumb") =/= nomatch),
    ?assert(string:find(ReconsiderationHtml, "inboxUnreadBadge") =/= nomatch),
    ?assert(string:find(ReconsiderationJs, "loadPreview") =/= nomatch),
    ?assert(string:find(ReconsiderationJs, "renderLifecycleState") =/= nomatch),
    ?assert(string:find(ReconsiderationJs, "reconsiderationLifecycleHint") =/= nomatch),
    ?assert(string:find(Html, "Cases / \x{6848}\x{5377}\x{5165}\x{53e3}\x{4e0e}\x{5de5}\x{4f5c}\x{53f0}") =/= nomatch),
    ?assert(string:find(IndexHtml, "/view/cases.html") =/= nomatch),
    ?assert(string:find(IndexHtml, "inboxUnreadBadge") =/= nomatch),
    ?assert(string:find(IndexHtml, "/view/inbox.html") =/= nomatch),
    ?assert(string:find(IndexHtml, "btnFileCase") =:= nomatch),
    ?assert(contains_codepoints(IndexHtml, [19977, 30465, 20845, 37096])),
    ?assert(contains_codepoints(IndexHtml, [27969, 31243, 22270])),
    ?assert(string:find(AppCss, "min-height: 100vh") =/= nomatch),
    ?assert(string:find(AppCss, "text-decoration: none;") =/= nomatch),
    ?assert(string:find(AppCss, "transition: all") =:= nomatch),
    ?assert(string:find(AppCss, ".btn:focus-visible") =/= nomatch),
    ?assert(string:find(AppCss, ".composer input:focus-visible") =/= nomatch),
    ?assert(string:find(AppCssWithoutMinHeight, "height: 100vh") =:= nomatch),
    ?assert(string:find(CaseCss, "grid-template-columns: repeat(2, minmax(0, 1fr));") =:= nomatch),
    ?assert(string:find(CaseCss, ":focus-visible") =/= nomatch),
    ?assert(string:find(CaseCss, ".contextHelp") =/= nomatch),
    ?assert(string:find(CaseCss, "min-height: 220px;") =:= nomatch),
    ?assert(string:find(CaseCss, ".emptyState") =/= nomatch),
    ?assert(string:find(CaseCss, ".objectSummaryMeta") =/= nomatch),
    ?assert(string:find(AppJs, "btnFileCase") =:= nomatch),
    ?assert(string:find(CaseJs, "emptyStateMarkup") =/= nomatch),
    ?assert(string:find(CaseJs, "\x{5148}\x{770b}\x{4efb}\x{52a1}\x{8be6}\x{60c5}") =/= nomatch),
    ?assert(string:find(CaseJs, "objectSummaryCard") =/= nomatch),
    ?assert(string:find(TaskJs, "setEmptyState") =/= nomatch),
    ?assert(string:find(TaskJs, "taskPrimaryPathHint") =/= nomatch),
    ?assert(string:find(TaskJs, "objectSummaryCard") =/= nomatch),
    ?assert(string:find(TaskJs, "renderRunAttempts") =/= nomatch),
    ?assert(string:find(TaskJs, "renderFactReports") =/= nomatch),
    ?assert(string:find(GovernanceJs, "setEmptyState") =/= nomatch),
    ?assert(string:find(GovernanceJs, "\x{8fd4}\x{56de}\x{4efb}\x{52a1}\x{8be6}\x{60c5}") =/= nomatch),
    ?assert(string:find(InboxJs, "return_to") =/= nomatch),
    ?assert(string:find(InboxJs, "\x{6848}\x{5377}\x{6d88}\x{606f}") =/= nomatch),
    ?assert(string:find(TopbarJs, "/api/inbox/unread-count") =/= nomatch),
    ?assert(string:find(TopbarJs, "return_label") =/= nomatch),
    ?assert(string:find(GovernanceJs, "objectSummaryCard") =/= nomatch),
    ?assert(contains_codepoints(AppJs, [25171, 24320, 25991, 26723])),
    ?assert(contains_codepoints(AppJs, [25552, 31034, 65306]))
  after
    reset_web_runtime(),
    process_flag(trap_exit, PrevTrap)
  end,
  ok.
