-module(openagentic_cli_main).
-export([usage/0]).

usage() ->
  io:format(
    "openagentic (Erlang)\\n\\n"
    "Usage:\\n"
    "  openagentic run [flags] <prompt>\\n"
    "  openagentic chat [flags]\\n"
    "  openagentic workflow [flags] [--dsl <path>] <prompt>\\n\\n"
    "  openagentic web [flags] [--web-bind <ip>] [--web-port <port>]\\n\\n"
    "Defaults:\\n"
    "  - Reads .env in project dir (if present)\\n"
    "  - Project dir defaults to current directory\\n"
    "  - Streaming defaults to on\\n"
    "  - Colors default to on (set NO_COLOR=1 to disable)\\n\\n"
    "Flags:\\n"
    "  --protocol <responses|legacy>\\n"
    "  --model <model>\\n"
    "  --api-key <key>\\n"
    "  --base-url <url>\\n"
    "  --api-key-header <header>\\n"
    "  --cwd <dir> (legacy alias; prefer --project-dir)\\n"
    "  --project-dir <dir>\\n"
    "  --resume <session_id>\\n"
    "  --permission <bypass|deny|prompt|default>\\n"
    "  --stream\\n"
    "  --no-stream\\n"
    "  --color\\n"
    "  --no-color\\n"
    "  --render-markdown (only affects non-stream output)\\n"
    "  --no-render-markdown\\n"
    "  --openai-store <bool>\\n"
    "  --no-openai-store\\n"
    "  --max-steps <1..200>\\n"
    "  --context-limit <n>\\n"
    "  --reserved <n>\\n"
    "  --input-limit <n>\\n"
    "  --dsl <path> (workflow DSL; default: workflows/three-provinces-six-ministries.v1.json)\\n\\n"
    "  --web-bind <ip> (web UI bind; default: 127.0.0.1)\\n"
    "  --web-port <port> (web UI port; default: 8088)\\n\\n"
    "Env/.env keys:\\n"
    "  OPENAI_API_KEY (required)\\n"
    "  OPENAI_BASE_URL (optional)\\n"
    "  OPENAI_MODEL or MODEL (optional)\\n"
    "  OPENAI_API_KEY_HEADER (optional)\\n"
    "  OPENAI_STORE (optional)\\n",
    []
  ).
