-module(openagentic_runtime_query_setup).
-export([prepare_query_context/3]).
-define(DEFAULT_MAX_STEPS, 50).
-define(DEFAULT_TIMEOUT_MS, 60000).
prepare_query_context(Prompt, Opts1, TimeContext) ->
  RootDir = openagentic_runtime_utils:ensure_list(maps:get(session_root, Opts1, openagentic_paths:default_session_root())),
  Metadata0 = openagentic_runtime_utils:ensure_map(maps:get(session_metadata, Opts1, #{})),
  Metadata = Metadata0#{time_context => TimeContext},
  Resume0 = maps:get(resume_session_id, Opts1, maps:get(resumeSessionId, Opts1, maps:get(<<"resume_session_id">>, Opts1, maps:get(<<"resumeSessionId">>, Opts1, undefined)))),
  Resume1 = case Resume0 of undefined -> <<>>; null -> <<>>; _ -> string:trim(openagentic_runtime_utils:to_bin(Resume0)) end,
  Resume = case Resume1 of <<"undefined">> -> <<>>; _ -> Resume1 end,
  Cwd = maps:get(cwd, Opts1, openagentic_runtime_utils:ensure_list(openagentic_runtime_paths:file_get_cwd_safe())),
  ProjectDir = openagentic_runtime_utils:ensure_list(maps:get(project_dir, Opts1, maps:get(projectDir, Opts1, Cwd))),
  EventSink = maps:get(event_sink, Opts1, maps:get(eventSink, Opts1, undefined)),
  ApiKey = maps:get(api_key, Opts1, maps:get(<<"api_key">>, Opts1, undefined)),
  Model = maps:get(model, Opts1, maps:get(<<"model">>, Opts1, undefined)),
  BaseUrl = maps:get(base_url, Opts1, maps:get(<<"base_url">>, Opts1, undefined)),
  TimeoutMs = maps:get(timeout_ms, Opts1, maps:get(<<"timeout_ms">>, Opts1, ?DEFAULT_TIMEOUT_MS)),
  ProviderRetry = maps:get(provider_retry, Opts1, maps:get(providerRetry, Opts1, #{})),
  IncludePartial = maps:get(include_partial_messages, Opts1, maps:get(includePartialMessages, Opts1, false)),
  OpenAiStore0 = openagentic_runtime_options:pick_opt(Opts1, [openai_store, openAiStore, <<"openai_store">>, <<"openAiStore">>, default_store, defaultStore, <<"default_store">>, <<"defaultStore">>]),
  OpenAiStore = openagentic_runtime_options:to_bool_default(OpenAiStore0, true),
  ApiKeyHeader0 = openagentic_runtime_options:pick_opt(Opts1, [api_key_header, apiKeyHeader, <<"api_key_header">>, <<"apiKeyHeader">>]),
  ApiKeyHeader = case string:trim(openagentic_runtime_utils:to_bin(ApiKeyHeader0)) of <<>> -> undefined; <<"undefined">> -> undefined; V -> V end,
  Protocol0 = maps:get(protocol, Opts1, maps:get(provider_protocol, Opts1, maps:get(providerProtocol, Opts1, maps:get(provider_protocol_override, Opts1, maps:get(providerProtocolOverride, Opts1, maps:get(<<"protocol">>, Opts1, maps:get(<<"provider_protocol">>, Opts1, maps:get(<<"providerProtocol">>, Opts1, undefined)))))))),
  Protocol = openagentic_provider_protocol:normalize(Protocol0),
  ProviderMod = case maps:get(provider_mod, Opts1, undefined) of undefined -> case Protocol of legacy -> openagentic_openai_chat_completions; responses -> openagentic_openai_responses end; M -> M end,
  SystemPrompt0 = maps:get(system_prompt, Opts1, maps:get(systemPrompt, Opts1, maps:get(<<"system_prompt">>, Opts1, maps:get(<<"systemPrompt">>, Opts1, undefined)))),
  SystemPrompt1 = string:trim(openagentic_runtime_utils:to_bin(SystemPrompt0)),
  SystemPrompt2 = case SystemPrompt1 of <<"undefined">> -> <<>>; _ -> SystemPrompt1 end,
  SystemPrompt = openagentic_time_context:compose_system_prompt(SystemPrompt2, TimeContext),
  TaskAgents = maps:get(task_agents, Opts1, maps:get(taskAgents, Opts1, [])),
  AgentsVar = openagentic_task_agents:render_agents_for_prompt(TaskAgents),
  ToolMods = maps:get(tools, Opts1, openagentic_runtime_options:default_tools()),
  WorkspaceDirOpt = openagentic_runtime_options:pick_opt(Opts1, [workspace_dir, workspaceDir, <<"workspace_dir">>, <<"workspaceDir">>]),
  ToolSchemas = openagentic_tool_schemas:responses_tools(ToolMods, #{project_dir => ProjectDir, workspace_dir => WorkspaceDirOpt, directory => Cwd, cwd => Cwd, agents => AgentsVar}),
  Registry = openagentic_tool_registry:new(ToolMods),
  UserAnswerer = maps:get(user_answerer, Opts1, undefined),
  PermissionGate0 = maps:get(permission_gate, Opts1, openagentic_permissions:default(UserAnswerer)),
  PermissionGate = openagentic_runtime_permissions:effective_permission_gate(Opts1, PermissionGate0, UserAnswerer),
  AllowedTools = maps:get(allowed_tools, Opts1, undefined),
  TaskProgressEmitter = maps:get(task_progress_emitter, Opts1, maps:get(taskProgressEmitter, Opts1, undefined)),
  TaskRunner0 = maps:get(task_runner, Opts1, undefined),
  HookEngine = maps:get(hook_engine, Opts1, maps:get(hookEngine, Opts1, #{})),
  ToolOutputArtifacts = maps:get(tool_output_artifacts, Opts1, maps:get(toolOutputArtifacts, Opts1, #{})),
  MaxSteps = maps:get(max_steps, Opts1, ?DEFAULT_MAX_STEPS),
  ResumeMaxEvents = maps:get(resume_max_events, Opts1, maps:get(resumeMaxEvents, Opts1, 1000)),
  ResumeMaxBytes = maps:get(resume_max_bytes, Opts1, maps:get(resumeMaxBytes, Opts1, 2000000)),
  TaskRunner = case TaskRunner0 of undefined -> openagentic_runtime_options:auto_task_runner(TaskAgents, Opts1); _ -> TaskRunner0 end,
  SupportsPrevDefault = case Protocol of legacy -> false; responses -> true end,
  SupportsPrev0 = maps:get(supports_previous_response_id, Opts1, maps:get(supportsPreviousResponseId, Opts1, SupportsPrevDefault)),
  SupportsPrev = case SupportsPrev0 of true -> true; false -> false; _ -> SupportsPrevDefault end,
  CompactionCfg = openagentic_runtime_utils:ensure_map(maps:get(compaction, Opts1, maps:get(<<"compaction">>, Opts1, #{}))),
  #{prompt => Prompt, opts => Opts1, time_context => TimeContext, root => RootDir, metadata => Metadata, resume => Resume, cwd => Cwd, project_dir => ProjectDir, event_sink => EventSink, api_key => ApiKey, model => Model, base_url => BaseUrl, timeout_ms => TimeoutMs, provider_retry => ProviderRetry, include_partial_messages => IncludePartial, openai_store => OpenAiStore, api_key_header => ApiKeyHeader, protocol => Protocol, provider_mod => ProviderMod, system_prompt => SystemPrompt, task_agents => TaskAgents, tool_schemas => ToolSchemas, registry => Registry, permission_gate => PermissionGate, allowed_tools => AllowedTools, user_answerer => UserAnswerer, task_progress_emitter => TaskProgressEmitter, task_runner => TaskRunner, hook_engine => HookEngine, tool_output_artifacts => ToolOutputArtifacts, max_steps => MaxSteps, resume_max_events => ResumeMaxEvents, resume_max_bytes => ResumeMaxBytes, compaction => CompactionCfg, supports_previous_response_id => SupportsPrev, workspace_dir_opt => WorkspaceDirOpt}.
